package com.vedubox.commonlibraries.model.enums;

public enum MessageType {
    SUPPORT_TICKET_CREATED_EVENT,
    QANDA_QUESTION_CREATED_EVENT,
    QANDA_QUESTION_ANSWERED_EVENT,
    EXAM_CREATED_EVENT,
    ANNOUNCEMENT_CREATED_EVENT,
    HOMEWORK_CREATED_EVENT,
    COURSE_ASSIGNED_EVENT,
    SINGLE_USER_CREATED_EVENT,
    BULK_USER_CREATED_EVENT,
    SEND_REGISTRATION_CONFIRMATION_COMMAND,
    COURSE_COMPLETED_EVENT,
    SEND_COURSE_COMPLETED_CERTIFICATE_COMMAND,
    LIVELESSON_CREATED_EVENT,
    LIVELESSON_CANCELLED_EVENT,
    LIVELESSON_UPDATED_EVENT,
    LIVELESSON_PARTICIPANT_CREATED_EVENT,
    SEND_LIVELESSON_REMINDER_COMMAND,
    PORTAL_PURCHASE_COMPLETED_EVENT,
}
